# Generated by Django 2.1.2 on 2019-03-11 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190311_1341'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerValidator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Choice')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='tracker',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='polls.Track'),
        ),
        migrations.AddField(
            model_name='answervalidator',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question'),
        ),
    ]
